name    'inkblot/racoon'
version '2.0.1'
source  'git://github.com/inkblot/puppet-racoon'
author  'inkblot'
license 'Apache 2.0'
summary 'Racoon IKE server'
description 'A puppet module for installing and configuring a Racoon IPSec IKE server'
project_page 'https://github.com/inkblot/puppet-racoon'

dependency 'puppetlabs/stdlib', '>= 4.1.0'
dependency 'ripienaar/module_data', '>= 0.0.1'
